### ISSUE TITLE
How can we work?

### ISSUE THREAD

**Issue by OskarMast** [silicia-apps/sio#15]
Hello.
Thanks for your following.
You followed me in github.
I have just seen your github profile.
I am Senior Full Stack developer with over 7 years of experience.
I think we can collaborate in coding and getting job.
I worked in Sapien Company of Califonia, but I lost job for now because the task was terminated.
So I am free now.I want to get job with you if possible.If you are interested in me, please let me know.
Thanks.

Best regards.

Oskar Mast

**Comment by silicia-apps** [comment]
HI,
I sent you an e-mail
